version: '3.3'
services:
  applied-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:3000
    volumes:
      - '..:/usr/src/app'
    command: 'npm run start:dev'
    networks:
      - applied-net

  applied-db:
    image: mysql:5.7.22
    container_name: applied-db
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: applied
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - applieddbdata:/var/lib/mysql
    networks:
      - applied-net

networks:
  applied-net:
    name: applied-net

volumes:
  applieddbdata:
    driver: local
